### ISSUE TITLE
erg文件只会存储主车的信息吗？

### ISSUE THREAD

**Issue by lsy234009** [danielhrisca/mfile#5]
请教一下，看了下解析出来的数据比如速度，加速度，距离等，貌似没有标识是哪个车的，都是主车的吗？erg文件里面存储了交通流车的数据吗，能解析出来吗？

**Comment by danielhrisca** [comment]
English?

**Comment by lsy234009** [comment]
Excuse me,I just want to ask how I can get the properties sucha as velocity of the  Ego car,should I use the  "Car.v" or “Vhcl.v”？Which prefix show the properties of the Ego?

**Comment by danielhrisca** [comment]
From what I know it's `Car.v`

**Comment by lsy234009** [comment]
> From what I know it's `Car.v`

Thanks~~
